spring:
  h2:
    console:
      enabled: true
  datasource:
#    url: jdbc:h2:file:~/demo/test;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:mydb
    username: digitalAssistant
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update

